# 基础镜像
FROM redis
# author
MAINTAINER services

# 挂载目录
VOLUME /home/services/redis
# 创建目录
RUN mkdir -p /home/services/redis
# 指定路径
WORKDIR /home/services/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/services/redis/redis.conf
